
name: main

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/10 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: stick
        run: |
          git config --local user.email "lend123@icloud.com"
          git config --local user.name "Zero00"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
